services:
  dbmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports: 
      - "3307:3306"
    networks:
      - app-network

  flask_api:
    build: ./python-api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - python-api:/app
    command: "python app.py"
    depends_on:
      - dbmysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  python-api:
